version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name CICD_CodeDeploy --s3-location s3://cicd2025/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src