version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name test --s3-location s3://citest-20250224/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src